### ISSUE TITLE
Update homepage

### ISSUE THREAD

**Issue by DarthGandalf** [lunarmodules/luafilesystem#163]
https://luarocks.org/modules/hisham/luafilesystem still points at the old keplerproject URL for documentation

Related: #162 #151

**Comment by Tieske** [comment]
@alerque I think you have the credentials to change this? let me know if there is anything I can do.

**Comment by alerque** [comment]
@Tieske I have the credentials for the *lunarmodules* user on LuaRocks, but that project hasn't been copied to or published under that user yet, it is still owned by @hishamhm. When it does get copied to our org user I'd be happy to update the meta information. I assume Hisham can also use admin access to update anything in the *lunarmodules* user too so that makes two of us, although I wouldn't mind also sharing the credentials. Do you have a GPG pubkey or some other way you'd like me to share that with you?

**Comment by hishamhm** [comment]
I've fixed the URL at luarocks.org!

**Comment by hishamhm** [comment]
(as for bus factor accounting, Leaf also has full admin access on luarocks.org, of course, so we're >1 on that as well)

**Comment by Tieske** [comment]
@alerque no need. If 🚌 hits, I think we're good.
